language: python
python:
  - "3.6"

install:
  - pip3 install -r requirements.txt
  # Down grade django for testing because 2.1 has errors on social auth app
  - pip install django==2.0
  - pip3 install coverage
  - pip3 install coveralls

script:
  - coverage run --source='.' ./manage.py test 
  # Code coverage
  - coverage report

notifications:
    slack: andela:Z0OEK3ImbHCX21YMYGIpIa92

after_script:
  - coveralls
