# Generated by Django 2.1 on 2018-10-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dzfyapyur/image/upload/v1540273709/widgetdocs/w35e2mpvs0xrp1zu3g2j.png'),
        ),
    ]
