# Generated by Django 2.1 on 2018-09-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='https://pixabay.com/en/avatar-person-neutral-man-blank-face-bud-159236/'),
        ),
    ]
