# Generated by Django 2.1 on 2018-09-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180919_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritearticle',
            name='favorite',
        ),
    ]
